// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euztqmewyommzcfshwmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1enRxbWV3eW9tbXpjZnNod214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTMzNDQsImV4cCI6MjA2NDA2OTM0NH0.KAyRXLGTGRgp4Noz7XVyFfGwGHkguYB29KJXHUlNLlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);